### ISSUE TITLE
Audio management broken by plugin on iOS

### ISSUE THREAD

**Issue by PawelBijok** [flutter-webrtc/flutter-webrtc#1119]
**Describe the bug**
Plugin in disturbing audio management on app start
Similar to #1078 

**To Reproduce**
Use app with plugin

**Expected behavior**
Plugin should initialize audio setting on peerConnection start

**Platform information**

* **Flutter version**: Flutter (Channel stable, 3.3.3, on macOS 12.5.1 21G83 darwin-x64, locale pl-PL)
* **Plugin version**: 0.9.9.+hotfix.1
* **OS**: iOS
* **OS version**: 16

**Comment by PawelBijok** [comment]
We use other Video Call providers that use native iOS. When audio management is used on app start (by webrtc) those providers stops working (freeze bugs)

**Comment by cloudwebrtc** [comment]
@PawelBijok Please test this branch https://github.com/flutter-webrtc/flutter-webrtc/pull/1122, I have fixed it in this PR

**Comment by PawelBijok** [comment]
I'll check it and let you know 👍

**Comment by PawelBijok** [comment]
@cloudwebrtc We tested your branch and  unfortunately this doesn't work for us. Other video providers still freezes

**Comment by cloudwebrtc** [comment]
@PawelBijok so what you really mean is https://github.com/flutter-webrtc/flutter-webrtc/pull/1120/files#diff-2496b27d4acaf6c7dc7482b1b221ccc92d20f720d1ca50d9aaffa404f0306564L96 The AVAudioSessionRouteChangeNotification event listener here causes the call of other apps to be interrupted (even if I don't start flutter-webrtc connection), am I understanding correctly?

**Comment by cloudwebrtc** [comment]
This means that if I move the AVAudioSessionRouteChangeNotification listener to when the first peer connetion is created, it will solve the issue you describe. Am I correct?

**Comment by PawelBijok** [comment]
Yes, 100% correct. Thats what we've been trying to achieve.

**Comment by PawelBijok** [comment]
https://github.com/flutter-webrtc/flutter-webrtc/pull/1120 I've updated my PR, with those changes our other video providers works. Please check if it is okay.

**Comment by cloudwebrtc** [comment]
hey, I added a judgment to the PR, it will only operate when RTCAudioSession.isActive, so the problem you described should be fixed, I opened the flutter-webrtc/example app when the zoom meeting was open, and the test results have been Will not affect the voip/music app anymore.
https://github.com/flutter-webrtc/flutter-webrtc/blob/main/common/darwin/Classes/FlutterWebRTCPlugin.m#L130

**Comment by MuZiLee** [comment]
You can experiment with localPC and remotePC Settings.

#import <AVFoundation/AVFoundation.h>

### localPC getUserMedia later
```
AVAudioSession *audioSession = [AVAudioSession sharedInstance];
      [[UIDevice currentDevice] setProximityMonitoringEnabled:NO];
          [audioSession overrideOutputAudioPort:AVAudioSessionPortOverrideNone error:nil];
    [audioSession setCategory:AVAudioSessionCategoryRecord error:nil];
    [audioSession setActive:YES error:nil];
```

### remotePC onAddStream later
```
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord
                                       withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker|
                                                   AVAudioSessionCategoryOptionDuckOthers|
                                                   AVAudioSessionCategoryOptionAllowBluetooth
                                             error:nil];
```
