### ISSUE TITLE
Android: Unable to getSources: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@13ceca6#0

### ISSUE THREAD

**Issue by obshksw** [flutter-webrtc/flutter-webrtc#320]
Calling navigator.getSources() crashes on Android only. It works fine on IOS.

```
navigator.getSources().then((List<dynamic> devices) {};
```

Stack:
```
E/MethodChannel#FlutterWebRTC.Method(23377): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method(23377): java.lang.IllegalArgumentException: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@b75b400
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:235)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.lambda$success$0$AnyThreadResult(AnyThreadResult.java:18)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.utils.-$$Lambda$AnyThreadResult$sxB97sGo761EWGEkbZEjApfiWl0.run(Unknown Source:4)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.post(AnyThreadResult.java:33)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.success(AnyThreadResult.java:18)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.getSources(FlutterWebRTCPlugin.java:934)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onMethodCall(FlutterWebRTCPlugin.java:183)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at android.os.MessageQueue.next(MessageQueue.java:343)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at android.os.Looper.loop(Looper.java:188)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at android.app.ActivityThread.main(ActivityThread.java:7604)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method(23377): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#FlutterWebRTC.Method(23201): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
I/flutter (23201): 15:27:45.004 [fatal] (logger) Dart error Unable to getSources: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@b75b400#0      WebRtcUtil.getDeviceList (package:live_app/util/webrtc/webrtc.dart:75:7)
```

```
[✓] Flutter (Channel unknown, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.2)
[✓] Connected device (2 available)
```

Tested on: Moto G7 Play (Android 10)
Also on Emulator: Pixel 2 API 30

Plugin version: 0.2.8

**Comment by obshksw** [comment]
In the `FlutterWebRTCPlugin.java` file, in the `getSources` function, replacing `result.success(array);` with this fixed it:
```
ConstraintsMap map = new ConstraintsMap();
map.putArray("sources", array.toArrayList());

result.success(map.toMap());
```

**Comment by obshksw** [comment]
Created a pull request: #321

**Comment by cloudwebrtc** [comment]
Thank you, PR has been merged.

**Comment by wer-mathurin** [comment]
Since this issue have been resolved and a fix have been applied to master can we mark is closed?

**Comment by obshksw** [comment]
I guess so, although it is not released yet, so the bug is still in the latest released version.
