### ISSUE TITLE
Jcenter.bintray dependency is down: Could not resolve io.grpc:grpc-api:[1.21.1]

### ISSUE THREAD

**Issue by RobotKSR** [flutter-webrtc/flutter-webrtc#944]
Hello!
This issue does not allow me to build project. It started to appear today, I am using latest version of flutter_webrtc lib (0.8.6).
Yesterday and all time before everything was working fine.

I think jcenter.bintray.com servers are totally down now, and probably you should remove jcenter() and make update to mavenCentral() in build.gradle / dependencies of flutter_webrtc library.

Here is my console log which I getting every time I try to build my project:
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_webrtc'.
> Could not resolve all artifacts for configuration ':flutter_webrtc:classpath'.
   > Could not resolve io.grpc:grpc-api:[1.21.1].
     Required by:
         project :flutter_webrtc > com.android.tools.build:gradle:7.1.1 > io.grpc:grpc-core:1.21.1
      > Failed to list versions for io.grpc:grpc-api.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/io/grpc/grpc-api/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/io/grpc/grpc-api/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_webrtc' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_webrtc' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by RobotKSR** [comment]
I fixed it and created PR: #945

**Comment by Rexobias** [comment]
I'm using this plugin locally and even with that change I'm still getting the exact same error.

Any idea?!

The project was working last Friday.

**Comment by RobotKSR** [comment]
> I'm using this plugin locally and even with that change I'm still getting the exact same error.
> 
> Any idea?!
> 
> The project was working last Friday.

 I suggest you to try not to use plugin locally. 
 Just import my fork in pubspec.yaml for now,  before main repository updated.
Like that:
```
  flutter_webrtc:
    git:
      url: https://github.com/RobotKSR/flutter-webrtc.git
      ref: 6bf2a6e885de1f7202bc03f5dfa2a1427902b49e
```

**Comment by Rexobias** [comment]
Meanwhile it started working again after making the same change you made on the PR. I also deleted the .gradle folder but I don't know if it changed something.

**Comment by RobotKSR** [comment]
Closing this issue because PR was commited to main. Thank you for cool plugin.
